package com.laddu.studentmanagerapp

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.TypeConverters
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(entities = [Student::class], version = 2)
@TypeConverters(Converters::class) //to handle the conversion of Date type to Long and vice versa
abstract class StudentDatabase: RoomDatabase() {
    abstract fun studentDao(): StudentDao //to manager the actions related to the student table

    companion object {
        @Volatile
        private var instance: StudentDatabase? = null

        val MIGRATION_1_2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE students ADD COLUMN admissionDate INTEGER NOT NULL DEFAULT 0")
            }
        }

        fun getInstance(context: Context): StudentDatabase? {
            if(instance == null) {
                instance = Room.databaseBuilder(
                    context.applicationContext,
                    StudentDatabase::class.java,
                    "student_database"
                ).addMigrations(MIGRATION_1_2).build()
            }
            return instance
        }
    }

} //implementation will be automatically generated by Room at compile time

//table name: students