package com.laddu.studentmanagerapp

import androidx.room.Database
import androidx.room.RoomDatabase

@Database(entities = [Student::class], version = 1)
abstract class StudentDatabase: RoomDatabase() {
    abstract fun studentDao(): StudentDao //to manager the actions related to the student table
} //implementation will be automatically generated by Room at compile time

//table name: students